from django.conf import settings
from django.urls import path
from . import views
from .views import edit_current_courses, get_majors_for_school, student_dashboard_view, tutor_students_list
from django.urls import path

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'), 
    path('student/dashboard/', views.student_dashboard_view, name='student_dashboard_view'),
    path('tutor/dashboard/', views.tutor_dashboard_view, name='tutor_dashboard_view'),
    path('logout/', views.user_logout, name='user_logout'),
    path('programs/', views.programs_view, name='programs'),
    path('programs/<int:school_id>/majors/', views.majors_view, name='majors'),
    path('majors/<int:major_id>/details/', views.major_detail, name='major_detail'),
    path('course/<int:course_id>/', views.course_detail, name='course_detail'),
    path('search/', views.search, name='search'),
    path('tutor/students/', tutor_students_list, name='tutor_students_list'),
    path('course/edit/<int:course_id>/', views.edit_current_courses, name='edit_course'),
    path('tutor/update_profile/', views.update_tutor_profile, name='update_tutor_profile'),
    path('student/completed_courses/', views.completed_courses, name='completed_courses'),
    path('student/add_completed_course/', views.add_completed_course, name='add_completed_course'),
    path('student/edit_completed_course/<int:pk>/', views.edit_completed_course, name='edit_completed_course'),
    path('student/remove_completed_course/<int:pk>/', views.remove_completed_course, name='remove_completed_course'),
    path('autocomplete/', views.autocomplete, name='autocomplete'),
    path('student/remaining_courses/', views.calculate_remaining_courses, name='calculate_remaining_courses'),
    path('student/update_profile/', views.update_student_profile, name='update_student_profile'),
    path('student/complete_course/<int:course_id>/', views.complete_course, name='complete_course'),
    path('study-plan/', views.study_plan_view, name='study_plan'), 
    path('student/dashboard/', student_dashboard_view, name='student_dashboard_view'),  
    path('student/dashboard/<int:year>/<str:semester>/', student_dashboard_view, name='student_dashboard_view_with_params'),
    path('tutor/dashboard/', views.tutor_dashboard, name='tutor_dashboard'),
    path('majors/<int:school_id>/', views.majors_view, name='majors'),
    path('major/<int:major_id>/', views.major_detail, name='major_detail'),
    path('tutor/students/', views.tutor_students_list, name='tutor_students_list'),
    path('student/dashboard/', student_dashboard_view, name='student_dashboard'),
    path('student/edit_current_courses/', edit_current_courses, name='edit_current_courses'),
    path('student/dashboard/<int:year>/<str:semester>/', views.student_dashboard_view, name='student_dashboard_view'),
    path('student/<int:student_id>/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('ajax/get_majors_for_school/', get_majors_for_school, name='ajax_get_majors_for_school'),
    path('inbox/', views.inbox, name='inbox'),
    path('send_message/', views.send_message, name='send_message'),
    path('send_message/<int:recipient_id>/', views.send_message, name='send_message_to_student'),
    path('get-completed-courses-data/', views.get_completed_courses_data, name='get_completed_courses_data'),
    path('student_dashboard/<int:student_id>/', views.tutor_student_dashboard_view, name='tutor_student_dashboard_view'),
    path('unread_messages_count/', views.get_unread_messages_count, name='get_unread_messages_count'),
    path('tutor_completed_courses/<int:student_id>/', views.tutor_view_completed_courses, name='tutor_view_completed_courses'),
    path('tutor/remaining_courses/<int:student_id>/', views.tutor_view_remaining_courses, name='tutor_view_remaining_courses'),
    path('study_plan/', views.study_plan_view, name='study_plan_view'),
    path('view_study_plan/', views.view_study_plan, name='view_study_plan'),
    path('view_study_plan/<int:student_id>/', views.view_study_plan, name='view_study_plan'),
    path('tutor_view_study_plan/<int:student_id>/', views.tutor_view_study_plan, name='tutor_view_study_plan'),
    path('delete_current_course/<int:course_id>/', views.delete_current_course, name='delete_current_course'),
    path('tutor/profile/<int:tutor_id>/', views.tutor_profile_view, name='tutor_profile_view'),

]
