# Generated by Django 4.0.3 on 2023-11-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_scholarship_student',
            field=models.BooleanField(default=False, verbose_name='Scholarship Student'),
        ),
    ]
