# Generated by Django 4.0.3 on 2023-12-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_app', '0003_tutorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('elective', 'Elective Course'), ('national_requirement', 'National Requirement'), ('english', 'English Course'), ('compulsory', 'Compulsory Course'), ('major_specific', 'Major Specific Course')], default='major', max_length=20, null=True),
        ),
    ]
